---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: CentOS-6.4
  driver_config:
    box: CentOS-6.4-x86_64-ja
    box_url: https://dl.dropboxusercontent.com/u/428597/vagrant_boxes/CentOS-6.4-x86_64-ja.box
    network:
      - [private_network, ip: 33.33.33.10]
    customize:
      cpus: 1 
      memory: 1024

- name: CentOS-5.9
  driver_config:
    box: CentOS-5.9-x86_64-ja
    box_url: https://dl.dropboxusercontent.com/u/428597/vagrant_boxes/CentOS-5.9-x86_64-ja.box
    network:
      - [private_network, ip: 33.33.33.10]
    customize:
      cpus: 1 
      memory: 1024

suites:
- name: default
  run_list: 
    - "recipe[apache2::default]"
  attributes: {}
